module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]

module.exports.description= [  "Camp beneath towering redwoods at Big Basin Redwoods State Park, and explore the park's many hiking trails and waterfalls.",
  "Pitch your tent at Acadia National Park and experience the stunning coastline of Maine, with rocky beaches, towering cliffs, and breathtaking ocean views.",
    "Experience the beauty of the Grand Tetons at Grand Teton National Park, with its towering peaks, pristine lakes, and abundant wildlife.",
    "Camp in the remote wilderness of Denali National Park and Preserve, where you can explore six million acres of unspoiled tundra and enjoy stunning views of Mount Denali.",
      "Escape to the Smoky Mountains at Great Smoky Mountains National Park, with its lush forests, cascading waterfalls, and stunning mountain vistas.",
        "Camp along the Colorado River at the Grand Canyon National Park and marvel at one of the world's most awe-inspiring natural wonders.",
          "Experience the rugged beauty of Arches National Park, with its iconic rock formations, arches, and spires, and enjoy hiking, rock climbing, and stargazing.",
            "Discover the beauty of Zion National Park, with its towering sandstone cliffs, narrow slot canyons, and stunning waterfalls.",
          "Camp in the picturesque Yosemite Valley at Yosemite National Park, and experience the park's stunning waterfalls, towering granite cliffs, and ancient giant sequoias.",
            "Pitch your tent in the Badlands National Park and explore the park's otherworldly landscapes of eroded buttes, pinnacles, and spires.",
            "Escape to the tranquil beauty of Isle Royale National Park, located on a remote island in Lake Superior, and enjoy hiking, kayaking, and wildlife watching.",
            "Experience the beauty of the Olympic National Park, with its rugged coastline, glacier-capped mountains, and lush rainforests.",
              "Camp in the heart of the Great Basin National Park and enjoy the park's stunning views of the night sky, as well as its unique geological features and ancient bristlecone pine forests.",
                "Explore the rugged beauty of Canyonlands National Park, with its deep canyons, towering mesas, and stunning views of the Colorado River.",
                  "Pitch your tent at Big Sur Campground and explore the rugged coastline, towering redwoods, and picturesque beaches of California's Big Sur.",
                    "Discover the beauty of Glacier Bay National Park and Preserve, with its stunning fjords, glaciers, and abundant wildlife, including humpback whales and grizzly bears.",
                      "Camp in the heart of the Red Rock Canyon National Conservation Area and explore the park's stunning sandstone formations, hiking trails, and rock climbing routes.",
                        "Experience the beauty of the Florida Keys at Bahia Honda State Park, with its crystal-clear waters, white sand beaches, and abundant marine life.",
                          "Escape to the tranquility of the Porcupine Mountains Wilderness State Park in Michigan, with its stunning forests, waterfalls, and miles of hiking trails.",
                            "Pitch your tent in the stunning Chugach State Park in Alaska and experience the park's rugged beauty, glaciers, and abundant wildlife, including bears, moose, and bald eagles."
                ]
